version: '3'

services:

  php:
    image: php:8.1.7-fpm-buster
    restart: &restart-policy unless-stopped
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    restart: *restart-policy
    ports:
      - "8008:80"
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf